// <auto-generated />
using System;
using Ensz;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ensz.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ensz.Ország", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FővárosID")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Népesség")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Név")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Terület")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FővárosID");

                    b.ToTable("Országok");
                });

            modelBuilder.Entity("Ensz.Város", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Népesség")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Név")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Városok");
                });

            modelBuilder.Entity("Ensz.Ország", b =>
                {
                    b.HasOne("Ensz.Város", "Főváros")
                        .WithMany()
                        .HasForeignKey("FővárosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Főváros");
                });
#pragma warning restore 612, 618
        }
    }
}
